In [1]:
import pandas as pd

In [2]:
survey_data=pd.read_csv("survey_results_public.csv")
survey_data

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,...,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
0,1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
1,2,I am a student who is learning to code,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,19.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
2,3,"I am not primarily a developer, but I write co...",Yes,Never,The quality of OSS and closed source software ...,Employed full-time,Thailand,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,...,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,28.0,Man,No,Straight / Heterosexual,NaN,Yes,Appropriate in length,Neither easy nor difficult
3,4,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,22.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
4,5,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Ukraine,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,30.0,Man,No,Straight / Heterosexual,White or of European descent;Multiracial,No,Appropriate in length,Easy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88878,88377,NaN,Yes,Less than once a month but more than once per ...,The quality of OSS and closed source software ...,"Not employed, and not looking for work",Canada,No,Primary/elementary school,NaN,...,NaN,Tech articles written by other developers;Tech...,NaN,Man,No,NaN,NaN,No,Appropriate in length,Easy
88879,88601,NaN,No,Never,The quality of OSS and closed source software ...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88880,88802,NaN,No,Never,NaN,Employed full-time,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88881,88816,NaN,No,Never,"OSS is, on average, of HIGHER quality than pro...","Independent contractor, freelancer, or self-em...",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88882,88863,NaN,Yes,Less than once per year,"OSS is, on average, of HIGHER quality than pro...","Not employed, and not looking for work",Spain,"Yes, full-time","Professional degree (JD, MD, etc.)","Computer science, computer engineering, or sof...",...,Somewhat less welcome now than last year,Tech articles written by other developers;Indu...,18.0,Man,No,Straight / Heterosexual,Hispanic or Latino/Latina;White or of European...,No,Appropriate in length,Easy

In [18]:
survey=survey_data.set_index("Respondent")
survey

,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,...,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
Respondent,,,,,,,,,,,,,,,,,,,,,
1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,"Taught yourself a new language, framework, or ...",...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
2,I am a student who is learning to code,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,Taken an online course in programming or softw...,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,19.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
3,"I am not primarily a developer, but I write co...",Yes,Never,The quality of OSS and closed source software ...,Employed full-time,Thailand,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,"Taught yourself a new language, framework, or ...",...,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,28.0,Man,No,Straight / Heterosexual,NaN,Yes,Appropriate in length,Neither easy nor difficult
4,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,22.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
5,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Ukraine,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,...,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,30.0,Man,No,Straight / Heterosexual,White or of European descent;Multiracial,No,Appropriate in length,Easy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88377,NaN,Yes,Less than once a month but more than once per ...,The quality of OSS and closed source software ...,"Not employed, and not looking for work",Canada,No,Primary/elementary school,NaN,"Taught yourself a new language, framework, or ...",...,NaN,Tech articles written by other developers;Tech...,NaN,Man,No,NaN,NaN,No,Appropriate in length,Easy
88601,NaN,No,Never,The quality of OSS and closed source software ...,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88802,NaN,No,Never,NaN,Employed full-time,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88816,NaN,No,Never,"OSS is, on average, of HIGHER quality than pro...","Independent contractor, freelancer, or self-em...",NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88863,NaN,Yes,Less than once per year,"OSS is, on average, of HIGHER quality than pro...","Not employed, and not looking for work",Spain,"Yes, full-time","Professional degree (JD, MD, etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,...,Somewhat less welcome now than last year,Tech articles written by other developers;Indu...,18.0,Man,No,Straight / Heterosexual,Hispanic or Latino/Latina;White or of European...,No,Appropriate in length,Easy

In [4]:
schema_data=pd.read_csv("survey_results_schema.csv")
schema_data

          Column                                       QuestionText
0     Respondent  Randomized respondent ID number (not in order ...
1     MainBranch  Which of the following options best describes ...
2       Hobbyist                            Do you code as a hobby?
3    OpenSourcer        How often do you contribute to open source?
4     OpenSource  How do you feel about the quality of open sour...
..           ...                                                ...
80     Sexuality  Which of the following do you currently identi...
81     Ethnicity  Which of the following do you identify as? Ple...
82    Dependents  Do you have any dependents (e.g., children, el...
83  SurveyLength  How do you feel about the length of the survey...
84    SurveyEase  How easy or difficult was this survey to compl...

[85 rows x 2 columns]

In [5]:
schema=schema_data.set_index("Column")
schema

                                                   QuestionText
Column
Respondent    Randomized respondent ID number (not in order ...
MainBranch    Which of the following options best describes ...
Hobbyist                                Do you code as a hobby?
OpenSourcer         How often do you contribute to open source?
OpenSource    How do you feel about the quality of open sour...
...                                                         ...
Sexuality     Which of the following do you currently identi...
Ethnicity     Which of the following do you identify as? Ple...
Dependents    Do you have any dependents (e.g., children, el...
SurveyLength  How do you feel about the length of the survey...
SurveyEase    How easy or difficult was this survey to compl...

[85 rows x 1 columns]

In [6]:
survey.columns

Index(['MainBranch', 'Hobbyist', 'OpenSourcer', 'OpenSource', 'Employment',
       'Country', 'Student', 'EdLevel', 'UndergradMajor', 'EduOther',
       'OrgSize', 'DevType', 'YearsCode', 'Age1stCode', 'YearsCodePro',
       'CareerSat', 'JobSat', 'MgrIdiot', 'MgrMoney', 'MgrWant', 'JobSeek',
       'LastHireDate', 'LastInt', 'FizzBuzz', 'JobFactors', 'ResumeUpdate',
       'CurrencySymbol', 'CurrencyDesc', 'CompTotal', 'CompFreq',
       'ConvertedComp', 'WorkWeekHrs', 'WorkPlan', 'WorkChallenge',
       'WorkRemote', 'WorkLoc', 'ImpSyn', 'CodeRev', 'CodeRevHrs', 'UnitTests',
       'PurchaseHow', 'PurchaseWhat', 'LanguageWorkedWith',
       'LanguageDesireNextYear', 'DatabaseWorkedWith',
       'DatabaseDesireNextYear', 'PlatformWorkedWith',
       'PlatformDesireNextYear', 'WebFrameWorkedWith',
       'WebFrameDesireNextYear', 'MiscTechWorkedWith',
       'MiscTechDesireNextYear', 'DevEnviron', 'OpSys', 'Containers',
       'BlockchainOrg', 'BlockchainIs', 'BetterLife', 'ITperson', 'OffOn',
       'SocialMedia', 'Extraversion', 'ScreenName', 'SOVisit1st',
       'SOVisitFreq', 'SOVisitTo', 'SOFindAnswer', 'SOTimeSaved',
       'SOHowMuchTime', 'SOAccount', 'SOPartFreq', 'SOJobs', 'EntTeams',
       'SOComm', 'WelcomeChange', 'SONewContent', 'Age', 'Gender', 'Trans',
       'Sexuality', 'Ethnicity', 'Dependents', 'SurveyLength', 'SurveyEase'],
      dtype='object')

In [7]:
schema.loc["ConvertedComp","QuestionText"]

'Salary converted to annual USD salaries using the exchange rate on 2019-02-01, assuming 12 working months and 50 working weeks.'

In [7]:
survey["Gender"].unique()

array(['Man', nan, 'Woman',
       'Non-binary, genderqueer, or gender non-conforming',
       'Woman;Non-binary, genderqueer, or gender non-conforming',
       'Woman;Man;Non-binary, genderqueer, or gender non-conforming',
       'Woman;Man',
       'Man;Non-binary, genderqueer, or gender non-conforming'],
      dtype=object)

## 1. age 20-30 ,salary-15L ,Gender -Female

In [ ]:
-age 20to 30
-sal 15L
-gender female

In [8]:
agesalgen=(survey["Age"].between(20,30)) & (survey["ConvertedComp"]==1500000) & (survey["Gender"]=="Woman")

In [9]:
survey.loc[agesalgen,["Age","Gender","ConvertedComp"]]

Empty DataFrame
Columns: [Age, Gender, ConvertedComp]
Index: []

In [10]:
agesalgen=(survey["Age"].between(20,30)) & (survey["ConvertedComp"]==1500000)
survey.loc[agesalgen,["Age","Gender","ConvertedComp"]]

             Age Gender  ConvertedComp
Respondent
13615       27.0    Man      1500000.0
33237       25.0    Man      1500000.0
35274       28.0    Man      1500000.0
44313       28.0    Man      1500000.0
45282       26.0    Man      1500000.0
75580       27.0    Man      1500000.0

### 2.Developers who gets more than 15L, and are they satisfied in their working environment

In [ ]:
-earns > 15
-jobsatisfaction

In [27]:
schema.loc["JobSat","QuestionText"]

'How satisfied are you with your current job? (If you work multiple jobs, answer for the one you spend the most hours on.)'

In [28]:
survey["JobSat"].unique()

array([nan, 'Slightly satisfied', 'Slightly dissatisfied',
       'Neither satisfied nor dissatisfied', 'Very satisfied',
       'Very dissatisfied'], dtype=object)

In [31]:
survey.loc[survey["ConvertedComp"]>1500000 ,[ "JobSat"]]

                                        JobSat
Respondent
58                              Very satisfied
102                         Slightly satisfied
166                         Slightly satisfied
436                         Slightly satisfied
452                             Very satisfied
...                                        ...
88712                    Slightly dissatisfied
88815       Neither satisfied nor dissatisfied
88818                       Slightly satisfied
88874                           Very satisfied
88877                           Very satisfied

[839 rows x 1 columns]

In [20]:
survey.loc[survey["ConvertedComp"]>1500000 ,[ "JobSat"]].value_counts()

JobSat
Very satisfied                        335
Slightly satisfied                    279
Slightly dissatisfied                  98
Neither satisfied nor dissatisfied     72
Very dissatisfied                      55
dtype: int64

In [11]:
survey.loc[survey["ConvertedComp"]>1500000 ,[ "JobSat","ConvertedComp"]]

                                        JobSat  ConvertedComp
Respondent
58                              Very satisfied      2000000.0
102                         Slightly satisfied      2000000.0
166                         Slightly satisfied      2000000.0
436                         Slightly satisfied      2000000.0
452                             Very satisfied      2000000.0
...                                        ...            ...
88712                    Slightly dissatisfied      2000000.0
88815       Neither satisfied nor dissatisfied      2000000.0
88818                       Slightly satisfied      2000000.0
88874                           Very satisfied      2000000.0
88877                           Very satisfied      2000000.0

[839 rows x 2 columns]

In [61]:
survey["Country"].unique()

array(['United Kingdom', 'Bosnia and Herzegovina', 'Thailand',
       'United States', 'Ukraine', 'Canada', 'India', 'New Zealand',
       'Antigua and Barbuda', 'Germany', 'Australia',
       'Russian Federation', 'Brazil', 'Lithuania', 'Israel',
       'South Africa', 'Colombia', 'Turkey', 'Switzerland', 'Argentina',
       'Sri Lanka', 'Czech Republic', 'Denmark', 'Malaysia', 'Bangladesh',
       'Spain', 'Serbia', 'Poland', 'Sweden', 'China', 'France',
       'Netherlands', 'Italy', 'Philippines', 'Ireland', 'Pakistan',
       'Azerbaijan', 'Austria', 'Estonia', 'Croatia', 'South Korea',
       'Greece', 'Japan', 'Romania', 'Finland', 'Bulgaria', 'Viet Nam',
       'Slovenia', 'Iran', 'Belarus', 'Hungary', 'Latvia',
       'Hong Kong (S.A.R.)', 'United Arab Emirates', 'Portugal',
       'Nigeria', 'Norway', 'Nicaragua', 'Zimbabwe', 'Egypt', 'Mexico',
       'Dominican Republic', 'Guatemala', 'Chile', 'Ecuador', 'Ghana',
       'Uganda', 'Cambodia', 'Mauritius', 'Nepal', 'Singapore',
       'Sierra Leone', 'Republic of Moldova', 'Belgium', 'Armenia',
       'Afghanistan', 'Bahrain', 'Mongolia', 'Georgia', 'Cyprus', 'Kenya',
       'Luxembourg', 'Saudi Arabia', 'Cape Verde', 'Peru', 'Burundi',
       'Iraq', 'Slovakia', 'Algeria', 'Taiwan', 'Yemen', 'Indonesia',
       'Morocco', 'Libyan Arab Jamahiriya', 'Belize', 'Mali',
       'Trinidad and Tobago', 'Venezuela, Bolivarian Republic of...',
       'Panama', 'Lebanon', 'Tunisia', 'Kuwait', 'Andorra',
       "Côte d'Ivoire", 'Syrian Arab Republic', 'El Salvador', 'Cameroon',
       'Malta', 'Turkmenistan', 'Brunei Darussalam',
       'Other Country (Not Listed Above)', 'Costa Rica', 'Jordan',
       'Albania', 'Uzbekistan', 'Sudan', 'Kazakhstan',
       'The former Yugoslav Republic of Macedonia', 'Ethiopia',
       'Paraguay', 'Myanmar', 'Somalia', 'Guyana', 'Honduras', 'Qatar',
       'Jamaica', 'Fiji', 'Haiti', 'Democratic Republic of the Congo',
       'Benin', 'Namibia', 'Montenegro', 'Rwanda', 'Tajikistan',
       'Uruguay', 'Mauritania', 'Bolivia', 'Gabon', 'Liechtenstein',
       'United Republic of Tanzania', 'Kyrgyzstan',
       "Lao People's Democratic Republic", 'Madagascar', 'Guinea',
       'Republic of Korea', 'Cuba', 'Maldives', 'Monaco', 'North Korea',
       'Senegal', 'Angola', 'Iceland', 'Togo', 'Swaziland',
       'Congo, Republic of the...', 'Zambia', 'Oman', 'Timor-Leste',
       'Tonga', 'Djibouti', "Democratic People's Republic of Korea",
       'Niger', 'Mozambique', 'Botswana', 'Dominica', 'Papua New Guinea',
       'Barbados', 'Seychelles', 'Lesotho', 'Bahamas', 'Burkina Faso',
       'Saint Kitts and Nevis', 'Malawi', 'Liberia', 'Bhutan',
       'Saint Vincent and the Grenadines', 'San Marino',
       'Sao Tome and Principe', 'Chad', nan], dtype=object)

### 3.Does SAARC countries exist in the dataframe

In [15]:
SAARC_COUNTRIES=("Afghanistan","Bangladesh","Bhutan","India","Maldives","Nepal","Pakistan","Sri Lanka")
SAARC_COUNTRIES

('Afghanistan',
 'Bangladesh',
 'Bhutan',
 'India',
 'Maldives',
 'Nepal',
 'Pakistan',
 'Sri Lanka')

In [30]:
survey.loc[survey["Country"].isin(SAARC_COUNTRIES)]

,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,...,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
Respondent,,,,,,,,,,,,,,,,,,,,,
8,I code primarily as a hobby,Yes,Less than once per year,"OSS is, on average, of HIGHER quality than pro...","Not employed, but looking for work",India,NaN,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...","Taught yourself a new language, framework, or ...",...,A lot more welcome now than last year,Tech articles written by other developers;Indu...,24.0,Man,No,Straight / Heterosexual,NaN,NaN,Appropriate in length,Neither easy nor difficult
10,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,India,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)",NaN,NaN,...,Somewhat less welcome now than last year,Tech articles written by other developers;Tech...,NaN,NaN,NaN,NaN,NaN,Yes,Too long,Difficult
15,I am a student who is learning to code,Yes,Never,"OSS is, on average, of HIGHER quality than pro...","Not employed, but looking for work",India,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,Taken an online course in programming or softw...,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,20.0,Man,No,NaN,NaN,Yes,Too long,Neither easy nor difficult
34,I am a student who is learning to code,Yes,Never,"OSS is, on average, of HIGHER quality than pro...","Not employed, but looking for work",Sri Lanka,No,Primary/elementary school,NaN,Taken an online course in programming or softw...,...,Just as welcome now as I felt last year,Tech articles written by other developers,17.0,Man,NaN,Bisexual,South Asian,Yes,Too short,Neither easy nor difficult
42,I am a developer by profession,Yes,Less than once a month but more than once per ...,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Bangladesh,No,"Secondary school (e.g. American high school, G...",NaN,Taken a part-time in-person course in programm...,...,Somewhat more welcome now than last year,Tech articles written by other developers;Tech...,30.0,Man,No,Straight / Heterosexual,Middle Eastern,NaN,Appropriate in length,Easy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
81624,NaN,Yes,Less than once a month but more than once per ...,"OSS is, on average, of HIGHER quality than pro...",Retired,Bangladesh,"Yes, full-time","Professional degree (JD, MD, etc.)","Information systems, information technology, o...",Participated in online coding competitions (e....,...,A lot more welcome now than last year,Tech articles written by other developers,NaN,"Non-binary, genderqueer, or gender non-conforming",Yes,NaN,NaN,Yes,Appropriate in length,Easy
83862,NaN,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,India,"Yes, full-time","Bachelor’s degree (BA, BS, B.Eng., etc.)",NaN,Participated in a hackathon,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,24.0,Man,No,Straight / Heterosexual,NaN,Yes,Too long,Neither easy nor difficult
84299,NaN,Yes,Never,The quality of OSS and closed source software ...,Employed full-time,India,"Yes, full-time","Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,Taken an online course in programming or softw...,...,Somewhat more welcome now than last year,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
86012,NaN,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,India,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)","Another engineering discipline (ex. civil, ele...","Taught yourself a new language, framework, or ...",...,Not applicable - I did not use Stack Overflow ...,Industry news about technologies you're intere...,24.0,Man,No,NaN,South Asian,NaN,Appropriate in length,Easy
88182,NaN,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed part-time,Pakistan,NaN,"Secondary school (e.g. American high school, G...",NaN,Taken an online course in programming or softw...,...,Not applicable - I did not use Stack Overflow ...,Courses on technologies you're interested in,NaN,Man,No,Straight / Heterosexual,NaN,Yes,Too short,Neither easy nor difficult

In [16]:
survey.loc[survey["Country"].isin(SAARC_COUNTRIES),["Country"]]

               Country
Respondent
8                India
10               India
15               India
34           Sri Lanka
42          Bangladesh
...                ...
81624       Bangladesh
83862            India
84299            India
86012            India
88182         Pakistan

[11257 rows x 1 columns]

######                                         ( or )

In [17]:
survey.loc[survey["Country"].isin(["Afghanistan","Bangladesh","Bhutan","India","Maldives","Nepal","Pakistan","Sri Lanka"])]

,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,...,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
Respondent,,,,,,,,,,,,,,,,,,,,,
8,I code primarily as a hobby,Yes,Less than once per year,"OSS is, on average, of HIGHER quality than pro...","Not employed, but looking for work",India,NaN,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...","Taught yourself a new language, framework, or ...",...,A lot more welcome now than last year,Tech articles written by other developers;Indu...,24.0,Man,No,Straight / Heterosexual,NaN,NaN,Appropriate in length,Neither easy nor difficult
10,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,India,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)",NaN,NaN,...,Somewhat less welcome now than last year,Tech articles written by other developers;Tech...,NaN,NaN,NaN,NaN,NaN,Yes,Too long,Difficult
15,I am a student who is learning to code,Yes,Never,"OSS is, on average, of HIGHER quality than pro...","Not employed, but looking for work",India,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,Taken an online course in programming or softw...,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,20.0,Man,No,NaN,NaN,Yes,Too long,Neither easy nor difficult
34,I am a student who is learning to code,Yes,Never,"OSS is, on average, of HIGHER quality than pro...","Not employed, but looking for work",Sri Lanka,No,Primary/elementary school,NaN,Taken an online course in programming or softw...,...,Just as welcome now as I felt last year,Tech articles written by other developers,17.0,Man,NaN,Bisexual,South Asian,Yes,Too short,Neither easy nor difficult
42,I am a developer by profession,Yes,Less than once a month but more than once per ...,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Bangladesh,No,"Secondary school (e.g. American high school, G...",NaN,Taken a part-time in-person course in programm...,...,Somewhat more welcome now than last year,Tech articles written by other developers;Tech...,30.0,Man,No,Straight / Heterosexual,Middle Eastern,NaN,Appropriate in length,Easy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
81624,NaN,Yes,Less than once a month but more than once per ...,"OSS is, on average, of HIGHER quality than pro...",Retired,Bangladesh,"Yes, full-time","Professional degree (JD, MD, etc.)","Information systems, information technology, o...",Participated in online coding competitions (e....,...,A lot more welcome now than last year,Tech articles written by other developers,NaN,"Non-binary, genderqueer, or gender non-conforming",Yes,NaN,NaN,Yes,Appropriate in length,Easy
83862,NaN,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,India,"Yes, full-time","Bachelor’s degree (BA, BS, B.Eng., etc.)",NaN,Participated in a hackathon,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,24.0,Man,No,Straight / Heterosexual,NaN,Yes,Too long,Neither easy nor difficult
84299,NaN,Yes,Never,The quality of OSS and closed source software ...,Employed full-time,India,"Yes, full-time","Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,Taken an online course in programming or softw...,...,Somewhat more welcome now than last year,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
86012,NaN,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,India,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)","Another engineering discipline (ex. civil, ele...","Taught yourself a new language, framework, or ...",...,Not applicable - I did not use Stack Overflow ...,Industry news about technologies you're intere...,24.0,Man,No,NaN,South Asian,NaN,Appropriate in length,Easy
88182,NaN,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed part-time,Pakistan,NaN,"Secondary school (e.g. American high school, G...",NaN,Taken an online course in programming or softw...,...,Not applicable - I did not use Stack Overflow ...,Courses on technologies you're interested in,NaN,Man,No,Straight / Heterosexual,NaN,Yes,Too short,Neither easy nor difficult

### 4.Female Developers those earns more than 10L and thier age when they first code

In [ ]:
-gender female
-earns > 10L
-their age when they first code

In [33]:
schema.loc["Age1stCode","QuestionText"]

'At what age did you write your first line of code or program? (E.g., webpage, Hello World, Scratch project)'

In [39]:
survey.loc[((survey["Gender"]=="Woman") & (survey["ConvertedComp"]>1000000)),["Age1stCode"]]

           Age1stCode
Respondent
789                 9
1758               16
6561               16
6939                8
9592               16
...               ...
80200              17
84247              17
85193              25
86327              10
86825              20

[68 rows x 1 columns]

In [12]:
survey.loc[((survey["Gender"]=="Woman") & (survey["ConvertedComp"]>1000000)),["Age1stCode","Gender","ConvertedComp"]]

           Age1stCode Gender  ConvertedComp
Respondent
789                 9  Woman      2000000.0
1758               16  Woman      2000000.0
6561               16  Woman      2000000.0
6939                8  Woman      1152000.0
9592               16  Woman      2000000.0
...               ...    ...            ...
80200              17  Woman      2000000.0
84247              17  Woman      1440000.0
85193              25  Woman      2000000.0
86327              10  Woman      2000000.0
86825              20  Woman      2000000.0

[68 rows x 3 columns]

### 5.Working Location and Edulevel of developers who gets 20L

In [ ]:
-dev earns = 20L
-their working location
-their edlevel

In [41]:
schema.loc["WorkLoc","QuestionText"]

'Where would you prefer to work?'

In [49]:
survey.loc[(survey["ConvertedComp"] == 2000000),["EdLevel","WorkLoc"]]

                                                EdLevel WorkLoc
Respondent
58             Bachelor’s degree (BA, BS, B.Eng., etc.)    Home
102            Bachelor’s degree (BA, BS, B.Eng., etc.)  Office
166            Bachelor’s degree (BA, BS, B.Eng., etc.)    Home
436            Bachelor’s degree (BA, BS, B.Eng., etc.)  Office
452              I never completed any formal education    Home
...                                                 ...     ...
88712          Bachelor’s degree (BA, BS, B.Eng., etc.)    Home
88815       Master’s degree (MA, MS, M.Eng., MBA, etc.)  Office
88818                                  Associate degree  Office
88874          Bachelor’s degree (BA, BS, B.Eng., etc.)  Office
88877          Bachelor’s degree (BA, BS, B.Eng., etc.)  Office

[709 rows x 2 columns]

In [13]:
survey.loc[(survey["ConvertedComp"] == 2000000),["EdLevel","WorkLoc","ConvertedComp"]]

                                                EdLevel WorkLoc  ConvertedComp
Respondent
58             Bachelor’s degree (BA, BS, B.Eng., etc.)    Home      2000000.0
102            Bachelor’s degree (BA, BS, B.Eng., etc.)  Office      2000000.0
166            Bachelor’s degree (BA, BS, B.Eng., etc.)    Home      2000000.0
436            Bachelor’s degree (BA, BS, B.Eng., etc.)  Office      2000000.0
452              I never completed any formal education    Home      2000000.0
...                                                 ...     ...            ...
88712          Bachelor’s degree (BA, BS, B.Eng., etc.)    Home      2000000.0
88815       Master’s degree (MA, MS, M.Eng., MBA, etc.)  Office      2000000.0
88818                                  Associate degree  Office      2000000.0
88874          Bachelor’s degree (BA, BS, B.Eng., etc.)  Office      2000000.0
88877          Bachelor’s degree (BA, BS, B.Eng., etc.)  Office      2000000.0

[709 rows x 3 columns]